### ISSUE TITLE
关于外参初始化的一个小问题

### ISSUE THREAD

**Issue by qiaozhijian** [xieqi1/VINS-Mono-noted#4]
https://github.com/xieqi1/VINS-Mono-noted/blob/ac404455447693e0aa102cdc5389efb2ed38e050/vins_estimator/src/initial/initial_ex_rotation.cpp#L84

请问这里不是应该使用findEssentialMat求解本质矩阵吗？我试了一下用这个函数，求出的R和原来的不一样

**Comment by xieqi1** [comment]
印象中E矩阵和F矩阵本质上就相差一个内参，然后这里都把点转移到了归一化相机坐标系，所以调用的这个findFundamentalMat求出来的就是E矩阵了，你自己使用可能也需要注意一下输入的点是像素坐标系还是归一化相机坐标系

**Comment by qiaozhijian** [comment]
谢谢，我觉得您说得对，归一化坐标系相当于K矩阵是单位矩阵，E矩阵和F矩阵相同
